"""Shadow table transformation — convert product users table for Auth Gateway sync."""

from __future__ import annotations

from . import ShadowConfig, ShadowReport


class ShadowTableTransformer:
    """Generates and applies SQL to convert a product's users table into a shadow table."""

    def __init__(self, config: ShadowConfig):
        self.config = config

    def generate_sql(self) -> list[str]:
        """Generate SQL statements for shadow table transformation."""
        statements = []

        for col in self.config.drop_columns:
            statements.append(
                f"ALTER TABLE {self.config.users_table} "
                f"DROP COLUMN IF EXISTS {col};"
            )

        for col in self.config.add_columns:
            statements.append(
                f"ALTER TABLE {self.config.users_table} "
                f"ADD COLUMN IF NOT EXISTS {col.name} {col.type} "
                f"DEFAULT {col.default};"
            )

        if any(c.name == "synced_at" for c in self.config.add_columns):
            statements.append(
                f"UPDATE {self.config.users_table} SET synced_at = NOW();"
            )

        statements.append(
            f"COMMENT ON TABLE {self.config.users_table} IS "
            f"'Shadow table synced from Auth Gateway. READ-ONLY for auth data.';"
        )

        return statements

    def transform(self, conn, dry_run: bool = True) -> ShadowReport:
        """Generate and optionally apply shadow table SQL."""
        report = ShadowReport()
        report.sql = self.generate_sql()

        if dry_run:
            return report

        cursor = conn.cursor()
        for stmt in report.sql:
            cursor.execute(stmt)
        conn.commit()
        cursor.close()

        report.applied = True
        return report

    def generate_migration_file(self, output_path: str) -> None:
        """Generate a SQL migration file for DBA review."""
        sql = self.generate_sql()
        with open(output_path, "w") as f:
            f.write("-- Migration: Convert users to shadow table\n")
            f.write("-- Generated by auth-gateway migration script\n")
            f.write("-- UUIDs preserved, FK references unchanged\n\n")
            f.write("BEGIN;\n\n")
            for stmt in sql:
                f.write(f"{stmt}\n\n")
            f.write("COMMIT;\n")
