// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/auth.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_ValidateToken_FullMethodName                    = "/auth.AuthService/ValidateToken"
	AuthService_GetUser_FullMethodName                          = "/auth.AuthService/GetUser"
	AuthService_CheckPermission_FullMethodName                  = "/auth.AuthService/CheckPermission"
	AuthService_IntrospectToken_FullMethodName                  = "/auth.AuthService/IntrospectToken"
	AuthService_CreateUser_FullMethodName                       = "/auth.AuthService/CreateUser"
	AuthService_Login_FullMethodName                            = "/auth.AuthService/Login"
	AuthService_InitPasswordlessRegistration_FullMethodName     = "/auth.AuthService/InitPasswordlessRegistration"
	AuthService_CompletePasswordlessRegistration_FullMethodName = "/auth.AuthService/CompletePasswordlessRegistration"
	AuthService_SendOTP_FullMethodName                          = "/auth.AuthService/SendOTP"
	AuthService_VerifyOTP_FullMethodName                        = "/auth.AuthService/VerifyOTP"
	AuthService_LoginWithOTP_FullMethodName                     = "/auth.AuthService/LoginWithOTP"
	AuthService_VerifyLoginOTP_FullMethodName                   = "/auth.AuthService/VerifyLoginOTP"
	AuthService_RegisterWithOTP_FullMethodName                  = "/auth.AuthService/RegisterWithOTP"
	AuthService_VerifyRegistrationOTP_FullMethodName            = "/auth.AuthService/VerifyRegistrationOTP"
	AuthService_IntrospectOAuthToken_FullMethodName             = "/auth.AuthService/IntrospectOAuthToken"
	AuthService_ValidateOAuthClient_FullMethodName              = "/auth.AuthService/ValidateOAuthClient"
	AuthService_GetOAuthClient_FullMethodName                   = "/auth.AuthService/GetOAuthClient"
	AuthService_SendEmail_FullMethodName                        = "/auth.AuthService/SendEmail"
	AuthService_GetUserApplicationProfile_FullMethodName        = "/auth.AuthService/GetUserApplicationProfile"
	AuthService_GetUserTelegramBots_FullMethodName              = "/auth.AuthService/GetUserTelegramBots"
	AuthService_SyncUsers_FullMethodName                        = "/auth.AuthService/SyncUsers"
	AuthService_GetApplicationAuthConfig_FullMethodName         = "/auth.AuthService/GetApplicationAuthConfig"
	AuthService_CreateTokenExchange_FullMethodName              = "/auth.AuthService/CreateTokenExchange"
	AuthService_RedeemTokenExchange_FullMethodName              = "/auth.AuthService/RedeemTokenExchange"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthService provides authentication and authorization operations for microservices
type AuthServiceClient interface {
	// ValidateToken validates a JWT access token and returns user information
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	// GetUser retrieves user information by ID
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	// CheckPermission checks if a user has specific permission
	CheckPermission(ctx context.Context, in *CheckPermissionRequest, opts ...grpc.CallOption) (*CheckPermissionResponse, error)
	// IntrospectToken provides detailed information about a token
	IntrospectToken(ctx context.Context, in *IntrospectTokenRequest, opts ...grpc.CallOption) (*IntrospectTokenResponse, error)
	// CreateUser creates a new user account
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	// Login authenticates a user with email/phone and password
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// InitPasswordlessRegistration initiates passwordless two-step registration
	InitPasswordlessRegistration(ctx context.Context, in *InitPasswordlessRegistrationRequest, opts ...grpc.CallOption) (*InitPasswordlessRegistrationResponse, error)
	// CompletePasswordlessRegistration completes registration after OTP verification
	CompletePasswordlessRegistration(ctx context.Context, in *CompletePasswordlessRegistrationRequest, opts ...grpc.CallOption) (*CompletePasswordlessRegistrationResponse, error)
	// SendOTP sends a one-time password to email
	SendOTP(ctx context.Context, in *SendOTPRequest, opts ...grpc.CallOption) (*SendOTPResponse, error)
	// VerifyOTP verifies a one-time password
	VerifyOTP(ctx context.Context, in *VerifyOTPRequest, opts ...grpc.CallOption) (*VerifyOTPResponse, error)
	// LoginWithOTP initiates passwordless login by sending OTP to email
	LoginWithOTP(ctx context.Context, in *LoginWithOTPRequest, opts ...grpc.CallOption) (*LoginWithOTPResponse, error)
	// VerifyLoginOTP completes passwordless login by verifying OTP
	VerifyLoginOTP(ctx context.Context, in *VerifyLoginOTPRequest, opts ...grpc.CallOption) (*VerifyLoginOTPResponse, error)
	// RegisterWithOTP initiates OTP-based registration by sending verification code
	RegisterWithOTP(ctx context.Context, in *RegisterWithOTPRequest, opts ...grpc.CallOption) (*RegisterWithOTPResponse, error)
	// VerifyRegistrationOTP completes OTP-based registration
	VerifyRegistrationOTP(ctx context.Context, in *VerifyRegistrationOTPRequest, opts ...grpc.CallOption) (*VerifyRegistrationOTPResponse, error)
	// IntrospectOAuthToken validates OAuth access token (RFC 7662)
	IntrospectOAuthToken(ctx context.Context, in *IntrospectOAuthTokenRequest, opts ...grpc.CallOption) (*IntrospectOAuthTokenResponse, error)
	// ValidateOAuthClient validates OAuth client credentials
	ValidateOAuthClient(ctx context.Context, in *ValidateOAuthClientRequest, opts ...grpc.CallOption) (*ValidateOAuthClientResponse, error)
	// GetOAuthClient retrieves OAuth client information by client_id
	GetOAuthClient(ctx context.Context, in *GetOAuthClientRequest, opts ...grpc.CallOption) (*GetOAuthClientResponse, error)
	// SendEmail sends an email using a specified template
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
	// GetUserApplicationProfile returns user's profile for a specific application
	GetUserApplicationProfile(ctx context.Context, in *GetUserAppProfileRequest, opts ...grpc.CallOption) (*UserAppProfileResponse, error)
	// GetUserTelegramBots returns user's Telegram bot access for an application
	GetUserTelegramBots(ctx context.Context, in *GetUserTelegramBotsRequest, opts ...grpc.CallOption) (*UserTelegramBotsResponse, error)
	// SyncUsers returns users updated after a given timestamp for shadow table sync
	SyncUsers(ctx context.Context, in *SyncUsersRequest, opts ...grpc.CallOption) (*SyncUsersResponse, error)
	// GetApplicationAuthConfig returns auth configuration for a specific application
	GetApplicationAuthConfig(ctx context.Context, in *GetApplicationAuthConfigRequest, opts ...grpc.CallOption) (*GetApplicationAuthConfigResponse, error)
	// CreateTokenExchange creates a one-time exchange code for cross-application SSO
	CreateTokenExchange(ctx context.Context, in *CreateTokenExchangeGrpcRequest, opts ...grpc.CallOption) (*CreateTokenExchangeGrpcResponse, error)
	// RedeemTokenExchange redeems an exchange code for tokens in the target application
	RedeemTokenExchange(ctx context.Context, in *RedeemTokenExchangeGrpcRequest, opts ...grpc.CallOption) (*RedeemTokenExchangeGrpcResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, AuthService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CheckPermission(ctx context.Context, in *CheckPermissionRequest, opts ...grpc.CallOption) (*CheckPermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPermissionResponse)
	err := c.cc.Invoke(ctx, AuthService_CheckPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) IntrospectToken(ctx context.Context, in *IntrospectTokenRequest, opts ...grpc.CallOption) (*IntrospectTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntrospectTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_IntrospectToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, AuthService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) InitPasswordlessRegistration(ctx context.Context, in *InitPasswordlessRegistrationRequest, opts ...grpc.CallOption) (*InitPasswordlessRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitPasswordlessRegistrationResponse)
	err := c.cc.Invoke(ctx, AuthService_InitPasswordlessRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CompletePasswordlessRegistration(ctx context.Context, in *CompletePasswordlessRegistrationRequest, opts ...grpc.CallOption) (*CompletePasswordlessRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompletePasswordlessRegistrationResponse)
	err := c.cc.Invoke(ctx, AuthService_CompletePasswordlessRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SendOTP(ctx context.Context, in *SendOTPRequest, opts ...grpc.CallOption) (*SendOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendOTPResponse)
	err := c.cc.Invoke(ctx, AuthService_SendOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyOTP(ctx context.Context, in *VerifyOTPRequest, opts ...grpc.CallOption) (*VerifyOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyOTPResponse)
	err := c.cc.Invoke(ctx, AuthService_VerifyOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) LoginWithOTP(ctx context.Context, in *LoginWithOTPRequest, opts ...grpc.CallOption) (*LoginWithOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginWithOTPResponse)
	err := c.cc.Invoke(ctx, AuthService_LoginWithOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyLoginOTP(ctx context.Context, in *VerifyLoginOTPRequest, opts ...grpc.CallOption) (*VerifyLoginOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyLoginOTPResponse)
	err := c.cc.Invoke(ctx, AuthService_VerifyLoginOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RegisterWithOTP(ctx context.Context, in *RegisterWithOTPRequest, opts ...grpc.CallOption) (*RegisterWithOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWithOTPResponse)
	err := c.cc.Invoke(ctx, AuthService_RegisterWithOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyRegistrationOTP(ctx context.Context, in *VerifyRegistrationOTPRequest, opts ...grpc.CallOption) (*VerifyRegistrationOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyRegistrationOTPResponse)
	err := c.cc.Invoke(ctx, AuthService_VerifyRegistrationOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) IntrospectOAuthToken(ctx context.Context, in *IntrospectOAuthTokenRequest, opts ...grpc.CallOption) (*IntrospectOAuthTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntrospectOAuthTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_IntrospectOAuthToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ValidateOAuthClient(ctx context.Context, in *ValidateOAuthClientRequest, opts ...grpc.CallOption) (*ValidateOAuthClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateOAuthClientResponse)
	err := c.cc.Invoke(ctx, AuthService_ValidateOAuthClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetOAuthClient(ctx context.Context, in *GetOAuthClientRequest, opts ...grpc.CallOption) (*GetOAuthClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOAuthClientResponse)
	err := c.cc.Invoke(ctx, AuthService_GetOAuthClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, AuthService_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUserApplicationProfile(ctx context.Context, in *GetUserAppProfileRequest, opts ...grpc.CallOption) (*UserAppProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAppProfileResponse)
	err := c.cc.Invoke(ctx, AuthService_GetUserApplicationProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUserTelegramBots(ctx context.Context, in *GetUserTelegramBotsRequest, opts ...grpc.CallOption) (*UserTelegramBotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserTelegramBotsResponse)
	err := c.cc.Invoke(ctx, AuthService_GetUserTelegramBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SyncUsers(ctx context.Context, in *SyncUsersRequest, opts ...grpc.CallOption) (*SyncUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncUsersResponse)
	err := c.cc.Invoke(ctx, AuthService_SyncUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetApplicationAuthConfig(ctx context.Context, in *GetApplicationAuthConfigRequest, opts ...grpc.CallOption) (*GetApplicationAuthConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApplicationAuthConfigResponse)
	err := c.cc.Invoke(ctx, AuthService_GetApplicationAuthConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CreateTokenExchange(ctx context.Context, in *CreateTokenExchangeGrpcRequest, opts ...grpc.CallOption) (*CreateTokenExchangeGrpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTokenExchangeGrpcResponse)
	err := c.cc.Invoke(ctx, AuthService_CreateTokenExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RedeemTokenExchange(ctx context.Context, in *RedeemTokenExchangeGrpcRequest, opts ...grpc.CallOption) (*RedeemTokenExchangeGrpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedeemTokenExchangeGrpcResponse)
	err := c.cc.Invoke(ctx, AuthService_RedeemTokenExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// AuthService provides authentication and authorization operations for microservices
type AuthServiceServer interface {
	// ValidateToken validates a JWT access token and returns user information
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	// GetUser retrieves user information by ID
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	// CheckPermission checks if a user has specific permission
	CheckPermission(context.Context, *CheckPermissionRequest) (*CheckPermissionResponse, error)
	// IntrospectToken provides detailed information about a token
	IntrospectToken(context.Context, *IntrospectTokenRequest) (*IntrospectTokenResponse, error)
	// CreateUser creates a new user account
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	// Login authenticates a user with email/phone and password
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// InitPasswordlessRegistration initiates passwordless two-step registration
	InitPasswordlessRegistration(context.Context, *InitPasswordlessRegistrationRequest) (*InitPasswordlessRegistrationResponse, error)
	// CompletePasswordlessRegistration completes registration after OTP verification
	CompletePasswordlessRegistration(context.Context, *CompletePasswordlessRegistrationRequest) (*CompletePasswordlessRegistrationResponse, error)
	// SendOTP sends a one-time password to email
	SendOTP(context.Context, *SendOTPRequest) (*SendOTPResponse, error)
	// VerifyOTP verifies a one-time password
	VerifyOTP(context.Context, *VerifyOTPRequest) (*VerifyOTPResponse, error)
	// LoginWithOTP initiates passwordless login by sending OTP to email
	LoginWithOTP(context.Context, *LoginWithOTPRequest) (*LoginWithOTPResponse, error)
	// VerifyLoginOTP completes passwordless login by verifying OTP
	VerifyLoginOTP(context.Context, *VerifyLoginOTPRequest) (*VerifyLoginOTPResponse, error)
	// RegisterWithOTP initiates OTP-based registration by sending verification code
	RegisterWithOTP(context.Context, *RegisterWithOTPRequest) (*RegisterWithOTPResponse, error)
	// VerifyRegistrationOTP completes OTP-based registration
	VerifyRegistrationOTP(context.Context, *VerifyRegistrationOTPRequest) (*VerifyRegistrationOTPResponse, error)
	// IntrospectOAuthToken validates OAuth access token (RFC 7662)
	IntrospectOAuthToken(context.Context, *IntrospectOAuthTokenRequest) (*IntrospectOAuthTokenResponse, error)
	// ValidateOAuthClient validates OAuth client credentials
	ValidateOAuthClient(context.Context, *ValidateOAuthClientRequest) (*ValidateOAuthClientResponse, error)
	// GetOAuthClient retrieves OAuth client information by client_id
	GetOAuthClient(context.Context, *GetOAuthClientRequest) (*GetOAuthClientResponse, error)
	// SendEmail sends an email using a specified template
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error)
	// GetUserApplicationProfile returns user's profile for a specific application
	GetUserApplicationProfile(context.Context, *GetUserAppProfileRequest) (*UserAppProfileResponse, error)
	// GetUserTelegramBots returns user's Telegram bot access for an application
	GetUserTelegramBots(context.Context, *GetUserTelegramBotsRequest) (*UserTelegramBotsResponse, error)
	// SyncUsers returns users updated after a given timestamp for shadow table sync
	SyncUsers(context.Context, *SyncUsersRequest) (*SyncUsersResponse, error)
	// GetApplicationAuthConfig returns auth configuration for a specific application
	GetApplicationAuthConfig(context.Context, *GetApplicationAuthConfigRequest) (*GetApplicationAuthConfigResponse, error)
	// CreateTokenExchange creates a one-time exchange code for cross-application SSO
	CreateTokenExchange(context.Context, *CreateTokenExchangeGrpcRequest) (*CreateTokenExchangeGrpcResponse, error)
	// RedeemTokenExchange redeems an exchange code for tokens in the target application
	RedeemTokenExchange(context.Context, *RedeemTokenExchangeGrpcRequest) (*RedeemTokenExchangeGrpcResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedAuthServiceServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedAuthServiceServer) CheckPermission(context.Context, *CheckPermissionRequest) (*CheckPermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPermission not implemented")
}
func (UnimplementedAuthServiceServer) IntrospectToken(context.Context, *IntrospectTokenRequest) (*IntrospectTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IntrospectToken not implemented")
}
func (UnimplementedAuthServiceServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) InitPasswordlessRegistration(context.Context, *InitPasswordlessRegistrationRequest) (*InitPasswordlessRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitPasswordlessRegistration not implemented")
}
func (UnimplementedAuthServiceServer) CompletePasswordlessRegistration(context.Context, *CompletePasswordlessRegistrationRequest) (*CompletePasswordlessRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompletePasswordlessRegistration not implemented")
}
func (UnimplementedAuthServiceServer) SendOTP(context.Context, *SendOTPRequest) (*SendOTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendOTP not implemented")
}
func (UnimplementedAuthServiceServer) VerifyOTP(context.Context, *VerifyOTPRequest) (*VerifyOTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyOTP not implemented")
}
func (UnimplementedAuthServiceServer) LoginWithOTP(context.Context, *LoginWithOTPRequest) (*LoginWithOTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginWithOTP not implemented")
}
func (UnimplementedAuthServiceServer) VerifyLoginOTP(context.Context, *VerifyLoginOTPRequest) (*VerifyLoginOTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyLoginOTP not implemented")
}
func (UnimplementedAuthServiceServer) RegisterWithOTP(context.Context, *RegisterWithOTPRequest) (*RegisterWithOTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWithOTP not implemented")
}
func (UnimplementedAuthServiceServer) VerifyRegistrationOTP(context.Context, *VerifyRegistrationOTPRequest) (*VerifyRegistrationOTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyRegistrationOTP not implemented")
}
func (UnimplementedAuthServiceServer) IntrospectOAuthToken(context.Context, *IntrospectOAuthTokenRequest) (*IntrospectOAuthTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IntrospectOAuthToken not implemented")
}
func (UnimplementedAuthServiceServer) ValidateOAuthClient(context.Context, *ValidateOAuthClientRequest) (*ValidateOAuthClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateOAuthClient not implemented")
}
func (UnimplementedAuthServiceServer) GetOAuthClient(context.Context, *GetOAuthClientRequest) (*GetOAuthClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOAuthClient not implemented")
}
func (UnimplementedAuthServiceServer) SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedAuthServiceServer) GetUserApplicationProfile(context.Context, *GetUserAppProfileRequest) (*UserAppProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserApplicationProfile not implemented")
}
func (UnimplementedAuthServiceServer) GetUserTelegramBots(context.Context, *GetUserTelegramBotsRequest) (*UserTelegramBotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTelegramBots not implemented")
}
func (UnimplementedAuthServiceServer) SyncUsers(context.Context, *SyncUsersRequest) (*SyncUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncUsers not implemented")
}
func (UnimplementedAuthServiceServer) GetApplicationAuthConfig(context.Context, *GetApplicationAuthConfigRequest) (*GetApplicationAuthConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplicationAuthConfig not implemented")
}
func (UnimplementedAuthServiceServer) CreateTokenExchange(context.Context, *CreateTokenExchangeGrpcRequest) (*CreateTokenExchangeGrpcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTokenExchange not implemented")
}
func (UnimplementedAuthServiceServer) RedeemTokenExchange(context.Context, *RedeemTokenExchangeGrpcRequest) (*RedeemTokenExchangeGrpcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RedeemTokenExchange not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CheckPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CheckPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckPermission(ctx, req.(*CheckPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_IntrospectToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntrospectTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).IntrospectToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_IntrospectToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).IntrospectToken(ctx, req.(*IntrospectTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_InitPasswordlessRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitPasswordlessRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).InitPasswordlessRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_InitPasswordlessRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).InitPasswordlessRegistration(ctx, req.(*InitPasswordlessRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CompletePasswordlessRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletePasswordlessRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CompletePasswordlessRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CompletePasswordlessRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CompletePasswordlessRegistration(ctx, req.(*CompletePasswordlessRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SendOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SendOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SendOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SendOTP(ctx, req.(*SendOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifyOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyOTP(ctx, req.(*VerifyOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_LoginWithOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginWithOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LoginWithOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_LoginWithOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LoginWithOTP(ctx, req.(*LoginWithOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyLoginOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyLoginOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyLoginOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifyLoginOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyLoginOTP(ctx, req.(*VerifyLoginOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RegisterWithOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWithOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RegisterWithOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RegisterWithOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RegisterWithOTP(ctx, req.(*RegisterWithOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyRegistrationOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRegistrationOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyRegistrationOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifyRegistrationOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyRegistrationOTP(ctx, req.(*VerifyRegistrationOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_IntrospectOAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntrospectOAuthTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).IntrospectOAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_IntrospectOAuthToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).IntrospectOAuthToken(ctx, req.(*IntrospectOAuthTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ValidateOAuthClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateOAuthClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ValidateOAuthClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ValidateOAuthClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ValidateOAuthClient(ctx, req.(*ValidateOAuthClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetOAuthClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOAuthClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetOAuthClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetOAuthClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetOAuthClient(ctx, req.(*GetOAuthClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUserApplicationProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAppProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUserApplicationProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetUserApplicationProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUserApplicationProfile(ctx, req.(*GetUserAppProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUserTelegramBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTelegramBotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUserTelegramBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetUserTelegramBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUserTelegramBots(ctx, req.(*GetUserTelegramBotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SyncUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SyncUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SyncUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SyncUsers(ctx, req.(*SyncUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetApplicationAuthConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationAuthConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetApplicationAuthConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetApplicationAuthConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetApplicationAuthConfig(ctx, req.(*GetApplicationAuthConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CreateTokenExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTokenExchangeGrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateTokenExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CreateTokenExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateTokenExchange(ctx, req.(*CreateTokenExchangeGrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RedeemTokenExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedeemTokenExchangeGrpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RedeemTokenExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RedeemTokenExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RedeemTokenExchange(ctx, req.(*RedeemTokenExchangeGrpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateToken",
			Handler:    _AuthService_ValidateToken_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AuthService_GetUser_Handler,
		},
		{
			MethodName: "CheckPermission",
			Handler:    _AuthService_CheckPermission_Handler,
		},
		{
			MethodName: "IntrospectToken",
			Handler:    _AuthService_IntrospectToken_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _AuthService_CreateUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "InitPasswordlessRegistration",
			Handler:    _AuthService_InitPasswordlessRegistration_Handler,
		},
		{
			MethodName: "CompletePasswordlessRegistration",
			Handler:    _AuthService_CompletePasswordlessRegistration_Handler,
		},
		{
			MethodName: "SendOTP",
			Handler:    _AuthService_SendOTP_Handler,
		},
		{
			MethodName: "VerifyOTP",
			Handler:    _AuthService_VerifyOTP_Handler,
		},
		{
			MethodName: "LoginWithOTP",
			Handler:    _AuthService_LoginWithOTP_Handler,
		},
		{
			MethodName: "VerifyLoginOTP",
			Handler:    _AuthService_VerifyLoginOTP_Handler,
		},
		{
			MethodName: "RegisterWithOTP",
			Handler:    _AuthService_RegisterWithOTP_Handler,
		},
		{
			MethodName: "VerifyRegistrationOTP",
			Handler:    _AuthService_VerifyRegistrationOTP_Handler,
		},
		{
			MethodName: "IntrospectOAuthToken",
			Handler:    _AuthService_IntrospectOAuthToken_Handler,
		},
		{
			MethodName: "ValidateOAuthClient",
			Handler:    _AuthService_ValidateOAuthClient_Handler,
		},
		{
			MethodName: "GetOAuthClient",
			Handler:    _AuthService_GetOAuthClient_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _AuthService_SendEmail_Handler,
		},
		{
			MethodName: "GetUserApplicationProfile",
			Handler:    _AuthService_GetUserApplicationProfile_Handler,
		},
		{
			MethodName: "GetUserTelegramBots",
			Handler:    _AuthService_GetUserTelegramBots_Handler,
		},
		{
			MethodName: "SyncUsers",
			Handler:    _AuthService_SyncUsers_Handler,
		},
		{
			MethodName: "GetApplicationAuthConfig",
			Handler:    _AuthService_GetApplicationAuthConfig_Handler,
		},
		{
			MethodName: "CreateTokenExchange",
			Handler:    _AuthService_CreateTokenExchange_Handler,
		},
		{
			MethodName: "RedeemTokenExchange",
			Handler:    _AuthService_RedeemTokenExchange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth.proto",
}
